### PR TITLE
Dev-1767 Add a PR templates on other projects

### PR DESCRIPTION
**Pull request by aloremia-freedom**
## Ticket references
- [Dev-1767 Add a PR templates on other projects](https://freedom.myjetbrains.com/youtrack/issue/Dev-1767)

## Summary of changes
Add the new universal PR template.

## Checklist
- [ ] bugfix
- [ ] new feature
- [ ] breaking change
- [ ] added unittests
- [x] changes introduced has been discussed and approved
- [ ] requires manual testing
- [ ] documentation has been updated

### CODE REVIEW

**Review by FerrielMelarpis — COMMENTED** [review]
Why do we need to move the PR template out of .github?

**Comment by aloremia-freedom** [comment]
@FerrielMelarpis We discussed it on the ticket with allen and tony, and we agreed to put the PR template in the root directory instead.

**Comment by FerrielMelarpis** [comment]
@pandafox @ToastedIceCream 
Why are GitHub-related files in the root directory?
If we plan on creating other GitHub-related files e.g. (CONTRIBUTING.md, ISSUE_TEMPLATE.md), are they also going to be placed in the root directory?
What's the reason for this?
In my perspective, they just clutter the project files since they are not really used by the project at all.

**Comment by pandafox** [comment]
Well, there are also other dot files that are under root, there shouldn't be too many that qualifies this.
1. The reason it's under root is, most git system would have compatibility for github, we'd like to use the same template if it does support it.
1-1. PR/Merge Request are common amongst all git systems. If the new system is not compatible, we'd need to create a new one for that system anyway. We can do clean up then.
2. I think it's fine adding 3 files specific to the project configuration.

**Review by FerrielMelarpis — APPROVED** [review]

**Comment by pandafox** [comment]
@aloremia-freedom next time please respond with the relevant link to the discussion to avoid confusion. A someone said so doesn't help the argument unless we understand the reasoning behind it.

**Pull request merged**
